---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc-rbd
  labels:
    appname: busybox
    dr-protect: true    
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 5Gi
