---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc-thin-csi2
  labels:
    appname: busybox
    instance: busybox-pvc-thin-csi2
    dr-protected-enabled: "false"            
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: thin-csi
  resources:
    requests:
      storage: 5Gi
