---
resources:
- busybox-pvc-thin-csi1.yaml
- busybox-pvc-thin-csi2.yaml
- busybox-deployment-thin-csi1.yaml
- busybox-deployment-thin-csi2.yaml
- busybox-pvc-rbd1.yaml
- busybox-pvc-rbd2.yaml
- busybox-deployment-rbd1.yaml
- busybox-deployment-rbd2.yaml

