---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-rbd1
  labels:
    appname: busybox
    instance: busybox-rbd1 
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: busybox-rbd1
  template:
    metadata:
      labels:
        deployment: busybox-rbd1
    spec:
      containers:
      - image: docker.io/library/busybox:stable
        imagePullPolicy: IfNotPresent
        name: busybox
        command: ['sh', '-c', 'trap exit TERM; while true; do echo $(date) | tee -a /mnt/test/outfile; sync; sleep 1; done']
        volumeMounts:
          - name: mypvc
            mountPath: /mnt/test
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: busybox-rbd-pvc1
