---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-thin-csi-pvc2
  labels:
    appname: busybox
    dr-protected-enabled: "false"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: thin-csi
  resources:
    requests:
      storage: 5Gi
