---
resources:
- busybox-pvc-thin-csi1.yaml
- busybox-deployment-thin-csi1.yaml
- busybox-pvc-thin-csi2.yaml
- busybox-deployment-thin-csi2.yaml
- busybox-rbd-pvc1.yaml
- busybox-rbd-deployment1.yaml
