---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc-cephfs
  labels:
    appname: busybox
    instance: busybox-cephfs
    dr-protected-enabled: "true"
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 5Gi
