---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc1
  labels:
    appname: busybox
    instance: busybox1
    placement: busybox-placement-1
    dr-protected-enabled: "true"    
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 5Gi
