---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc2
  labels:
    appname: busybox
    instance: busybox2
    placement: busybox-placement-1
    dr-protected-enabled: "true"            
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 5Gi
